#!/usr/bin/env bash
# Usage: find out by running:
#   ./run.sh -h

# Exit on error, undefined variable, or error in pipeline
set -euo pipefail
# Unmatched globs expand to nothing
shopt -s nullglob  

# Default argument values
dataUrl="http://localhost:5500/"
delimiter="|"
prefix=""
buildMiravi=true
strict=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    -u)
      dataUrl="$2"
      shift 2
      ;;
    -d)
      delimiter="$2"
      shift 2
      ;;
    -p)
      prefix="$2"
      shift 2
      ;;
    -n|--noMiraviBuild)
      buildMiravi=false
      shift
      ;;
    -s|--strict)
      strict=true
      shift
      ;;  
    -h|--help)
      echo "Usage: $0 [-u <dataUrl>] [-d <delimiter>] [-p prefix] [-n | --noMiraviBuild] [-s | --strict] [-h | --help]"
      echo "  <dataUrl>:     the base URL where the RDF output files will be served; default='http://localhost:5500/'"
      echo "  <delimiter>:   delimiter used to enter multiple values in one cell in the spreadsheets; default='|'"
      echo "  <prefix>:      prefix to paths; default=''"
      echo "  noMiraviBuild: do not build Miravi and delete previous build"
      echo "  strict:        do not take custom vocabulary into account"
      exit 1
      ;;
    -*)
      echo "Unknown option: $1"
      exit 1
      ;;
    *)
      echo "Unexpected argument: $1"
      exit 1
      ;;
  esac
done

# Paths to input and output directories and files
in_dir="${prefix}in"
in_shacl_dir="${prefix}in-shacl"
out_dir="${prefix}out"
template_schema_json="${in_shacl_dir}/template.schema.json"
queries_dir="${out_dir}/queries"
queries_combined_file="${queries_dir}/generated-queries.rq"
queries_split_dir="${queries_dir}/generated-queries"
rdf_dir="${out_dir}/serve-me"
miravi_main_dir="${prefix}node_modules/miravi/main"
miravi_initial_config_dir="miravi-initial-config"

rm -rf $out_dir

noInputFiles=false
inputs=("$in_dir"/*.xlsx)
if [ ${#inputs[@]} -eq 0 ]; then
  echo "❌ No input files found."
  noInputFiles=true
fi

noSchemaFile=false
schema=("$in_dir"/*.json)
if [ ${#inputs[@]} -eq 0 ]; then
  echo "❌ No schema file found."
  noSchemaFile=true
fi

if [[ "$noInputFiles" == false && "$noSchemaFile" == false ]]; then
  for input in "$in_dir"/*.xlsx; do
    base=$(basename "$input")
    echo "Processing file: $base"
    fileName="${base%.xlsx}"        # removes extension → file.xlsx → file

    echo "ℹ️  Processing file: $input"
    node ./src/dataxlsx-to-datajson.js -i $input -o $out_dir -d $delimiter

    if [[ "$strict" == false ]]; then
      echo "ℹ️  Enhancing schema with custom vocabulary from file: $input"
      node ./src/dataxlsx-to-enriched-schema.js -i $input -o $out_dir -s $template_schema_json
      echo "ℹ️  Generating file: $out_dir/$fileName.mapping.yml"
      node ./src/schema-to-yarrrml.js -i "$out_dir/$fileName-enriched-schema.json" -o "$out_dir/$fileName.mapping.yml" -s "$out_dir/$fileName.json"
     else
      echo "ℹ️  Strict mode enabled; skipping enhancement of schema with custom vocabulary."
      echo "ℹ️  Generating file: $out_dir/$fileName.mapping.yml"
      node ./src/schema-to-yarrrml.js -i "$template_schema_json" -o "$out_dir/$fileName.mapping.yml" -s "$out_dir/$fileName.json"
    fi

    echo "ℹ️  Generating file: $out_dir/$fileName.mapping.rml.ttl"
    npx @rmlio/yarrrml-parser -i "$out_dir/$fileName.mapping.yml" -o "$out_dir/$fileName.mapping.rml.ttl" -p

    # temporary solution because base is not generated by YARRRML Parser, and default base in RMLMapper doesn't end with /
    echo '@base <http://example.com/> .' | cat - "$out_dir/$fileName.mapping.rml.ttl" > "temp" && mv "temp" "$out_dir/$fileName.mapping.rml.ttl"

    echo "ℹ️  Generating file: $rdf_dir/$fileName.ttl"
    mkdir -p $rdf_dir
    java -jar ./rmlmapper-7.3.3-r374-all.jar -m $out_dir/$fileName.mapping.rml.ttl -o $rdf_dir/$fileName.ttl -s turtle
  done

  if [[ "$strict" == false ]]; then
      echo "ℹ️  Merging enriched schemas in: $out_dir"
      node ./src/merge-enriched-schemas.js -i "$out_dir" -o "$out_dir/mergedschema.json"
      echo "ℹ️  Generating combined queries file $queries_combined_file and split queries in $queries_split_dir"
      node ./src/schema-to-sparql.js -i "$out_dir/mergedschema.json" -o "$queries_combined_file" -s "$queries_split_dir"
     else
      echo "ℹ️  Strict mode enabled; skipping merging of schemas."
      echo "ℹ️  Generating combined queries file $queries_combined_file and split queries in $queries_split_dir"
      node ./src/schema-to-sparql.js -i "$template_schema_json" -o "$queries_combined_file" -s "$queries_split_dir"
    fi
  
else
  echo "ℹ️  Generating (empty) file $rdf_dir/empty.ttl."
  mkdir -p $rdf_dir
  echo "" > $rdf_dir/empty.ttl
  echo "ℹ️  Generating (empty) combined queries file $queries_combined_file and (no) split queries in $queries_split_dir"
  mkdir -p "$queries_dir"
  echo "" > "$queries_combined_file"
  mkdir -p "$queries_split_dir"
fi

echo "ℹ️  Preparing Miravi configuration in $miravi_main_dir"
node ./src/prepare-miravi-config.js -i "$miravi_initial_config_dir" -s "$queries_split_dir" -o "$miravi_main_dir" -u "$dataUrl" -d "$rdf_dir"

if [[ "$buildMiravi" == true ]]; then
  echo "ℹ️  Building Miravi in $miravi_main_dir into $miravi_main_dir/dist; see $miravi_main_dir/build.log for details..."
  (cd $miravi_main_dir && npm run build > build.log 2>&1)
else
  echo "ℹ️  Skipping Miravi build; deleting previous Miravi build..."
  rm -rf $miravi_main_dir/dist
fi