# Join CreatiefWerk → taal → SkosConcept
SELECT DISTINCT ?CreatiefWerk_url ?SkosConcept_url WHERE {
  ?CreatiefWerk_url a <https://schema.org/CreativeWork> .
  ?SkosConcept_url a <http://www.w3.org/2004/02/skos/core#Concept> .
  ?CreatiefWerk_url <https://schema.org/inLanguage> ?SkosConcept_url .
}
