# Join Licentie → type → SkosConcept
SELECT DISTINCT ?Licentie_url ?SkosConcept_url WHERE {
  ?Licentie_url a <http://purl.org/dc/terms/LicenseDocument> .
  ?SkosConcept_url a <http://www.w3.org/2004/02/skos/core#Concept> .
  ?Licentie_url <http://purl.org/dc/terms/type> ?SkosConcept_url .
}
